Django - 6/blog/urls.py
from django.urls import path

from blog import cb_views

app_name = 'blog'

urlpatterns = [
    # CBV blog
    path('', cb_views.BlogListView.as_view(), name='list'),
    path('<int:blog_pk>/', cb_views.BlogDetailView.as_view(), name='detail'),
    path('create/', cb_views.BlogCreateView.as_view(), name='create'),
    path('<int:pk>/update/', cb_views.BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', cb_views.BlogDeleteView.as_view(), name='delete'),
    path('comment/create/<int:blog_pk>/', cb_views.CommentCreateView.as_view(), name='comment_create'),
]

Django - 6/config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from member import views as member_views
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, RedirectView
from django.views import View

# class AboutView(TemplateView):
#     template_name = 'about.html'
#
# class TestView(View): # Django의 View 클래스 상속
#     def get(self, request):
#         return render(request, 'test_get.html')
#
#     def post(self, request):
#         return render(request, 'test_post.html')

from blog import cb_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('fb/', include('blog.fbv_urls')),

    # # CBV blog
    # path('', cb_views.BlogListView.as_view(), name='blog_list'),
    # path('<int:pk>/', cb_views.BlogDetailView.as_view(), name='blog_detail'),
    # path('create/', cb_views.BlogCreateView.as_view(), name='blog_create'),
    # path('<int:pk>/update/', cb_views.BlogUpdateView.as_view(), name='blog_update'),
    # path('<int:pk>/delete/', cb_views.BlogDeleteView.as_view(), name='blog_delete'),

    # FBV blog
    # path('', views.blog_list, name='blog_list'),
    # path('<int:pk>/', views.blog_detail, name="blog_detail"),
    # path('create/', views.blog_create, name='blog_create'),
    # path('<int:pk>/update/', views.blog_update, name='blog_update'),
    # path('<int:pk>/delete/', views.blog_delete, name='blog_delete'),

    # auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', member_views.sign_up, name='signup'),
    path('login/', member_views.login, name='login'),

    # path('test/', TestView.as_view(), name='test'),
    # # path('about', TemplateView.as_view(template_name='about.html'), name='about'),
    # path('about', AboutView.as_view(), name='about'),
    # path('redirect/', RedirectView.as_view(pattern_name='about'), name='redirect'),
    # path('redirect2/', lambda req: redirect('about')),

]

Django - 6/blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

from utils.models import TimestampModel


class Blog(models.Model):
    CATEGORY_CHOICES = (
        ('free', '자유'),
        ('travel', '여행'),
        ('cat', '고양이'),
        ('dog', '강아지')
    )

    category = models.CharField('카테고리', max_length=10, choices=CATEGORY_CHOICES , default='free')
    title = models.CharField('제목', max_length=100)
    content = models.TextField('본문')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    created_at = models.DateTimeField('작성일자', auto_now_add=True)
    updated_at = models.DateTimeField('작성일자', auto_now=True)

    # 제목이 노출되는 형식을 설정 [카테고리] 제목은 최대 10자까지
    def __str__(self):
        return f'[{self.get_category_display()}] {self.title[:10]}'

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'blog_pk': self.pk})

    class Meta:
        verbose_name = '블로그'
        verbose_name_plural = '블로그 목록'

class Comment(TimestampModel):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.CharField('본문', max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.blog.title} 댓글'

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글 목록'
        ordering = ['-created_at', '-id']

Django - 6/member/models.py
from django.db import models

# Create your models here.

Django - 6/utils/models.py
from django.db import models


class TimestampModel(models.Model):
    created_at = models.DateTimeField('작성일자', auto_now_add=True)
    updated_at = models.DateTimeField('수정일자', auto_now=True)

    class Meta:
        abstract = True

Django - 6/blog/forms.py
from django import forms
from blog.models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'content': '댓글'
        }

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', )

Django - 6/blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render,get_object_or_404,redirect,reverse
from blog.models import Blog
from blog.forms import BlogForm
from django.core.paginator import Paginator
from django.db.models import Q

from django.views.decorators.http import require_http_methods

@login_required()
@require_http_methods(['POST'])
def blog_delete(request, pk):
    # if request.method == 'POST':
    #     raise Http404

    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    blog.delete()

    return redirect(reverse('fb:list'))

def blog_list(request):
    blogs = Blog.objects.all().order_by('-created_at')

    q = request.GET.get('q')
    if q:
        blogs = blogs.filter(
            Q(title__icontains=q) |
            Q(content__icontains=q)
        )

        # blogs = blogs.filter(content__contains=q)

    # 한 페이지당 10개씩 보이도록
    paginator = Paginator(blogs, 10)

    page = request.GET.get('page')
    page_object = paginator.get_page(page)

    context = {
        'object_list': page_object.object_list,
        'page_obj': page_object,
    }

    return render(request, 'blog_list.html', context)

def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    context = { 'blog' : blog }
    return render(request, 'blog_detail.html', context)

@login_required()
def blog_create(request):
    # if not request.user.is_authenticated:
    #     return redirect('login')

    form = BlogForm(request.POST or None)
    if form.is_valid():
        blog = form.save(commit=False)
        blog.author = request.user
        blog.save()
        return redirect(reverse('fb:detail', kwargs={'pk': blog.pk}))

    context = {'form': form}
    return render(request, 'blog_form.html', context)

@login_required()
def blog_update(request, pk):
    blog = get_object_or_404(Blog, pk=pk, author=request.user)

    form = BlogForm(request.POST or None, instance=blog)
    if form.is_valid():
        blog = form.save()
        return redirect(reverse('fb:detail', kwargs={'pk': blog.pk}))

    context = {'blog': blog,
               'form' : form,
               }

    return render(request, 'blog_form.html', context)

Django - 6/member/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render,redirect
from django.conf import settings

from django.contrib.auth import login as django_login
from django.urls import reverse

def login(request):
    form = AuthenticationForm(request, request.POST or None)
    if form.is_valid():
        django_login(request, form.get_user())

        next = request.GET.get('next')
        if next:
            return redirect(next)

        return redirect(reverse('blog:list'))

    else:
        form = AuthenticationForm(request)

    context = {
        'form': form
    }

    return render(request, 'registration/login.html', context)

def sign_up(request):

    # username = request.POST.get('username')
    # password1 = request.POST.get('password1')
    # password2 = request.POST.get('password2')
    #
    # print('username', username)
    # print('password1', password1)
    # print('password2', password2)

# 비밀번호가 맞는지 / 비밀번호 정책에 올바른지(대소문자)
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(settings.LOGIN_URL)

    context = {
        'form': form
    }
    return render(request, 'registration/signup.html', context)

Django - 6/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>어바웃 페이지 입니다.</h1>
</body>
</html

Django - 6/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>블로그 프로젝트</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
</head>
<body>
  <nav class="d-flex justify-content-between py-2 px-4 bg-black text-white">
    <div>
      <a class="text-decoration-none text-white" href="{% url "blog:list" %}">홈</a>
    </div>
    <div style="text-align: right">
      {% if request.user.is_authenticated %}
        <form action="{% url 'logout' %}" method="POST" class="d-inline">
          {% csrf_token %}
          <button class="btn btn-danger btn-sm">로그아웃</button>
        </form>
        {{ request.user.username }}
      {% else %}
        <a href="{% url 'signup' %}">회원가입</a>
        <a href="{% url 'login' %}">로그인</a>
      {% endif %}
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <footer>

  </footer>
  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  {% block js %}{% endblock %}
</body>
</html>

Django - 6/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="mt-2 d-flex justify-content-between">
    <h1>{{ blog.title }}</h1>

    {% if request.user == blog.author or request.user.is_superuser %}
      <div>
        <a class="btn btn-sm btn-warning" href="{% url 'blog:update' blog.pk %}">수정</a>

        <form id="delete_form" action="{% url 'blog:delete' blog.pk %}" method="POST" style="display: inline">
          {% csrf_token %}
          <button type="button" id="delete_btn" class="btn btn-sm btn-danger">삭제</button>
        </form>
      </div>
    {% endif %}
  </div>

  <div style="text-align: right">
    {{ blog.author.username }}
  </div>
  <hr>
  <p>{{ blog.content }}</p>

  <hr>
  {% if request.user.is_authenticated %}
    <form method="post">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <div class="text-end">
        <button class="btn btn-primary">작성</button>
      </div>
    </form>
  {% endif %}

    <div class="mb-2" id="comment_wrapper">
        {% for comment in blog.comment_set.all %}
          <div>
            {{ comment.content }}
            <p class="text-end">
              <small>{{ comment.created_at | date:'Y-m-d H:i' }} | {{ comment.author.username }}</small>
            </p>
          </div>
        {% endfor %}
    </div>

    {% include 'pagination.html' with fragment="comment_wrapper" %}

  <hr>
  <a class="btn btn-sm btn-info" href="{% url 'blog:list' %}">목록</a>
{% endblock %}

{% block js %}
  <script>
    document.querySelector('#delete_btn').addEventListener('click', function() {
		  if(confirm('삭제하시겠습니까?')) {
			  document.querySelector('#delete_form').submit();
      }
    })
  </script>
{% endblock %}

Django - 6/templates/blog_form.html
{% extends 'base.html' %}
{%  block content %}
    <h1 class="mt-2">블로그 {{ sub_title }}</h1>
<form method="POST">
    {% csrf_token %}
    {{  form.as_p }}
    <button class="btn btn-primary">{% if btn_name %}
        {{ btn_name }}{% else %}저장{% endif %}
    </button>
</form>
{% endblock %}
{% block js %}
  {% include 'form-js.html' %}
{% endblock %}

Django - 6/templates/blog_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="mt-2">
    <h1 class="d-inline">블로그 목록</h1>
    <a href="{% url 'blog:create' %}" class="float-end btn btn-sm btn-primary">생성</a>
  </div>

  <hr>

  {% for blog in object_list %}
    <div class="my-1">
      <a href="{% url 'blog:detail' blog.pk %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
        [{{ blog.get_category_display }}] {{ blog.title }} - <small>{{ blog.created_at | date:"Y-m-d" }}</small>
      </a>
    </div>
  {% endfor %}

  <form method="get" class="my-3 d-flex">
    <input class="form-control-sm" name="q" type="text" placeholder="검색어를 입력하세요." value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">
    <button class="btn btn-sm btn-info ms-2">검색</button>
  </form>
    {% include 'pagination.html' %}
{% endblock %}

Django - 6/templates/form-js.html
<script>
    document.querySelectorAll('select, input , textarea').forEach(function(ele){
        ele.classList.add('form-control');
    })
</script>

Django - 6/templates/pagination.html
<div class="d-flex justify-content-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">&laquo; 첫번째</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">이전</a>
        </li>
      {% endif %}
      {#  현재페이지 -2 = 2 > 1보다 크면 #}
      {% if page_obj.number|add:-2 > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.number|add:-3 }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">&hellip;</a>
        </li>
      {% endif %}

      {# 10페이지까지 1~10 #}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item">
            <a class="page-link active" href="#">
              {{ i }}
            </a>
        </li>
  {#    현재페이지-3 < i < 현재페이지+3    #}
        {% elif i > page_obj.number|add:-3 and i < page_obj.number|add:3 %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {#  최대페이지(10) > 8(현재 페이지) + 2  #}
      {% if page_obj.paginator.num_pages > page_obj.number|add:2 %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.number|add:3 }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">&hellip;</a>
        </li>
      {% endif %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">다음</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">마지막
          &raquo;</a></li>
      {% endif %}
    </ul>
  </div>

Django - 6/templates/test_get.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <h1>테스트 겟</h1>
  <form method="post">
    {% csrf_token %}
    <button>포스트</button>
  </form>
</body>
</html>

Django - 6/templates/test_post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <h1>테스트 포스트</h1>
</body>
</html>