Django - 5/blog/urls.py
from django.urls import path

from blog import cb_views

app_name = 'blog'

urlpatterns = [
    # CBV blog
    path('', cb_views.BlogListView.as_view(), name='list'),
    path('<int:pk>/', cb_views.BlogDetailView.as_view(), name='detail'),
    path('create/', cb_views.BlogCreateView.as_view(), name='create'),
    path('<int:pk>/update/', cb_views.BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', cb_views.BlogDeleteView.as_view(), name='delete'),
]

Django - 5/blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

class Blog(models.Model):
    CATEGORY_CHOICES = (
        ('free', '자유'),
        ('travle', '여행'),
        ('cat', '고양이'),
        ('dog', '강아지')
    )

    category = models.CharField('카테고리', max_length=10, choices=CATEGORY_CHOICES , default='free')
    title = models.CharField('제목', max_length=100)
    content = models.TextField('본문')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    created_at = models.DateTimeField('작성일자', auto_now_add=True)
    updated_at = models.DateTimeField('작성일자', auto_now=True)

    # 제목이 노출되는 형식을 설정 [카테고리] 제목은 최대 10자까지
    def __str__(self):
        return f'[{self.get_category_display()}] {self.title[:10]}'

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = '블로그'
        verbose_name_plural = '블로그 목록'

Django - 5/blog/forms.py
from django import forms
from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', )

Django - 5/blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render,get_object_or_404,redirect,reverse
from blog.models import Blog
from blog.forms import BlogForm
from django.core.paginator import Paginator
from django.db.models import Q

from django.views.decorators.http import require_http_methods

@login_required()
@require_http_methods(['POST'])
def blog_delete(request, pk):
    # if request.method == 'POST':
    #     raise Http404

    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    blog.delete()

    return redirect(reverse('fb:list'))

def blog_list(request):
    blogs = Blog.objects.all().order_by('-created_at')

    q = request.GET.get('q')
    if q:
        blogs = blogs.filter(
            Q(title__icontains=q) |
            Q(content__icontains=q)
        )

        # blogs = blogs.filter(content__contains=q)

    # 한 페이지당 10개씩 보이도록
    paginator = Paginator(blogs, 10)

    page = request.GET.get('page')
    page_object = paginator.get_page(page)

    context = {
        'object_list': page_object.object_list,
        'page_obj': page_object,
    }

    return render(request, 'blog_list.html', context)

@login_required()
def blog_create(request):
    # if not request.user.is_authenticated:
    #     return redirect('login')

    form = BlogForm(request.POST or None)
    if form.is_valid():
        blog = form.save(commit=False)
        blog.author = request.user
        blog.save()
        return redirect(reverse('fb:detail', kwargs={'pk': blog.pk}))

    context = {'form': form}
    return render(request, 'blog_create.html', context)


def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    context = { 'blog' : blog }
    return render(request, 'blog_detail.html', context)

@login_required()
def blog_update(request, pk):
    blog = get_object_or_404(Blog, pk=pk, author=request.user)

    form = BlogForm(request.POST or None, instance=blog)
    if form.is_valid():
        blog = form.save()
        return redirect(reverse('fb:detail', kwargs={'pk': blog.pk}))

    context = {'blog': blog,
               'form' : form,
               }

    return render(request, 'blog_update.html', context)

Django - 5/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>블로그 프로젝트</title>
</head>
<body>
    <nav style="display: flex; justify-content: space-between">
        <div>
            <a href="{% url "blog:list" %}">홈</a>
        </div>
        <div style="text-align: right">
            {% if request.user.is_authenticated %}
                <form action="{%  url 'logout' %}" method="POST" style="display: inline">
                    {% csrf_token %}
                    <button>로그아웃</button>
                </form>
                {{ request.user.username }}
            {% else %}
	            <a href="{%  url 'signup' %}">회원가입</a>
	            <a href="{%  url 'login' %}">로그인</a>
            {% endif %}
        </div>
    </nav>
    {%  block content %}{% endblock %}

    <footer>

    </footer>
  {% block js %}{% endblock %}
</body>
</html>

Django - 5/templates/blog_create.html
{% extends 'base.html' %}
{%  block content %}
    <h1>블로그 작성</h1>
<form method="POST">
    {% csrf_token %}
    {{  form.as_p }}
    <button>생성</button>
</form>
{% endblock %}

Django - 5/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ blog.title }}</h1>

{#  {% if request.user == blog.author %}  #}
  {% if request.user == blog.author or request.user.is_superuser %}
    <div style="text-align: right">
      <a href="{% url 'blog:update' blog.pk %}">수정</a>

      <form id="delete_form" action="{% url 'blog:delete' blog.pk %}" method="POST" style="display: inline">
        {% csrf_token %}
        <button type="button" id="delete_btn">삭제</button>
      </form>
    </div>
  {% endif %}

  <div style="text-align: right">
    {{ blog.author.username }}
  </div>
  <hr>
  <p>{{ blog.content }}</p>


  <a href="{% url 'blog:list' %}">목록으로 돌아가기</a>
{% endblock %}

{% block js %}
  <script>
    document.querySelector('#delete_btn').addEventListener('click', function() {
		  if(confirm('삭제하시겠습니까?')) {
			  document.querySelector('#delete_form').submit();
      }
    })
  </script>
{% endblock %}

Django - 5/templates/blog_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>블로그 목록</h1>
    <p style="text-align: right">
    <a href="{% url 'blog:create' %}">생성</a>
    </p>

    {% for blog in object_list %}
        <p>
            <a href="{% url 'blog:detail' blog.pk %}">
{#                ({{ blog.id }}){{ blog.title }} - <small>{{ blog.created_at | date:"Y-m-d"}}</small>#}
                [{{ blog.get_category_display }}]{{ blog.title }} - <small>{{ blog.created_at | date:"Y-m-d"}}</small>
            </a>
        </p>
    {%  endfor %}

    {# 검색버튼 #}
    <form method="get" style="margin-bottom: 10px;">
        <input name="q" type="text" placeholder="검색어를 입력하세요." value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">>
        <button>검색</button>
    </form>

    <div>
        {% if page_obj.has_previous %} {# 이전 페이지가 존재할 경우 #}
            <a href="?page=1{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">&laquo; 첫번째</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">이전</a>
        {% endif %}

        {% if page_obj.number|add:-2 > 1 %}
            <a href="?page={{ page_obj.number|add:-3 }}{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">&hellip;</a>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <span>(현재페이지)</span>
            {% elif i > page_obj.number|add:-3 and i < page_obj.number|add:3 %}
                <a href="?page={{ i }}{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">{{ i }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:2 %}
            <a href="?page={{ page_obj.number|add:3 }}{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">&hellip;</a>
        {% endif %}

        {% if page_obj.has_next %}
                <a href="?page={{ page.object.next_page_number }}{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">다음</a>
                <a href="?page={{ page.object.paginator.num_pages }}{% if request.GET.q %}{{ request.GET.q }}{% endif %}&q=">마지막 &raquo;</a>
        {% endif %}
    </div>
{% endblock %}

Django - 5/templates/blog_update.html
{% extends 'base.html' %}
{%  block content %}
    <h1>블로그 수정</h1>
    <form method="POST">
        {% csrf_token %}
        {{  form.as_p }}
        <button>수정</button>
        
    </form>
{% endblock %}